version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fit_system_db
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app