# Test Profile
"%test":
  quarkus:
    log:
      level: INFO
      category:
        "io.pwii":
          level: DEBUG
    hibernate-orm:
      log:
        sql: true
  smallrye:
    jwt:
      sign:
        key:
          location: privatekey.pem
  mp:
    jwt:
      verify:
        publickey:
          location: publickey.pem
        issuer: http://localhost:8080
  fitsystem:
    config:
      token:
        expirationInSecs: 86400

# Dev Profile
"%dev":
  quarkus:
    banner:
      enabled: false
    log:
      level: INFO
      category:
        "io.demo":
          level: DEBUG
    datasource:
      db-kind: postgresql
      username: app
      password: app
      jdbc:
        url: jdbc:postgresql://localhost:5432/fit_system_db?stringtype=unspecified
    hibernate-orm:
      database:
          generation: none
      log:
        sql: true
    flyway:
      migrate-at-start: true
      locations: db/migration,db/testdata
    native:
      resources:
        includes: publickey.pem
    smallrye-openapi:
      info-title: FitSystem API (DEV)
      info-version: 1.0.0
      info-description: API for FIT SYSTEM management
      info-contact-email: mateusgoncalvespereira@gmail.com
      info-contact-name: Mateus
      info-contact-url: https://github.com/mateusgpereira/
      info-license-name: Apache 2.0
      info-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
    swagger-ui:
      always-include: true
  smallrye:
    jwt:
      sign:
        key:
          location: privatekey.pem
  mp:
    jwt:
      verify:
        publickey:
          location: publickey.pem
        issuer: http://localhost:8080
  fitsystem:
    config:
      token:
        expirationInSecs: 86400
