CREATE TYPE USER_ROLE AS ENUM ('INSTRUCTOR', 'ATHLETE');

CREATE TABLE gym_user (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE,
  age INT,
  password  VARCHAR(255) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  cpf VARCHAR(12) NOT NULL UNIQUE,
  height INT,
  weight DOUBLE PRECISION,
  user_role USER_ROLE NOT NULL,
  createdAt DATE NOT NULL DEFAULT CURRENT_DATE,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);