CREATE TYPE WORKOUT_CATEGORY AS ENUM ('LEGS', 'SHOULDERS', 'ARMS', 'BACK', 'ABDOMINALS', 'CHEST', 'TRICEPS', 'BICEPS', 'AEROBIC');

CREATE TABLE workout (
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  category WORKOUT_CATEGORY NOT NULL,
  code VARCHAR(1) NOT NULL, 
  createdAt DATE NOT NULL DEFAULT CURRENT_DATE,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  athlete_id BIGINT, 
  instructor_id BIGINT
);

ALTER TABLE IF EXISTS workout ADD CONSTRAINT FK_workout_athlete FOREIGN KEY (athlete_id) REFERENCES athlete;
ALTER TABLE IF EXISTS workout ADD CONSTRAINT FK_workout_instructor FOREIGN KEY (instructor_id) REFERENCES instructor;